name: MariaDB Integration Test

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup up java
        uses: actions/setup-java@v3
        with:
          java-version: '20'
          distribution: 'adopt'

      - name: Verify java version
        run: java -version

      - name: Verify maven version
        run: mvn -version


      - name: Set up MariaDB
        uses: getong/mariadb-action@v1.1
        with:
          host port: ${{ secrets.DB_PORT }}
          mysql database:  ${{ secrets.DB_NAME }}
          mysql user:  ${{ secrets.DB_USER }}
          mysql root password: ${{ secrets.DB_PASSWORD }}

      #          skip-checks: true


      - name: Build with Maven
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_PASS: ${{ secrets.DB_PASSWORD }}
          DB_PORT: ${{ secrets.DB_PORT }}
          FILE_PATH: spring-boot/users.csv
        run: |
          cd spring-boot
          mvn clean verify


      - name: Create Artifacts
        run: |
          mkdir artifacts
          cd artifacts

#          cp target/*.jar.original artifacts/
#
#      - name: Upload Artifacts
#        uses: actions/upload-artifact@v2
#        with:
#          name: java-artifacts
#          path: artifacts/
      - name: Upload artifact results
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: spring-boot/target/artifacts